import clouds_down from './clouds/clouds_down.bmp';
import clouds_east from './clouds/clouds_east.bmp';
import clouds_north from './clouds/clouds_north.bmp';
import clouds_south from './clouds/clouds_south.bmp';
import clouds_up from './clouds/clouds_up.bmp';
import clouds_west from './clouds/clouds_west.bmp';
import crate from './crate.jpg';
import door from './door/Door_Wood_001_basecolor.jpg';
import doorAmbientOcclusion from './door/Door_Wood_001_ambientOcclusion.jpg';
import doorHeight from './door/Door_Wood_001_height.png';
import doorMetallic from './door/Door_Wood_001_metallic.jpg';
import doorNormal from './door/Door_Wood_001_normal.jpg';
import doorOpacity from './door/Door_Wood_001_opacity.jpg';
import doorRoughness from './door/Door_Wood_001_roughness.jpg';
import gradient from './gradient.png';
import ice from './ice.png';
import matcap from './matcap/generator2.jpg';
import fiveTone from './tones/fiveTone.jpg';

export { clouds_down, clouds_east, clouds_north, clouds_south, clouds_up, clouds_west, crate, door, doorAmbientOcclusion, doorHeight, doorMetallic, doorNormal, doorOpacity, doorRoughness, gradient, ice, matcap, fiveTone };
